//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBMCatering.Negocio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OBMCatering.Negocio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El mensaje de la bitacora no puede ser nulo o vacio.
        /// </summary>
        internal static string BitacoraBL_Validaciones_MensajeNull {
            get {
                return ResourceManager.GetString("BitacoraBL_Validaciones_MensajeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de mensaje &apos;{0}&apos; es incorrecto o no es valido en el sistema.
        /// </summary>
        internal static string BitacoraBL_Validaciones_TipoInvalido {
            get {
                return ResourceManager.GetString("BitacoraBL_Validaciones_TipoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe un usuario valido para el nick &apos;{0}&apos;.
        /// </summary>
        internal static string BitacoraBL_Validaciones_UsuarioInvalido {
            get {
                return ResourceManager.GetString("BitacoraBL_Validaciones_UsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no puede ser nulo.
        /// </summary>
        internal static string BitacoraBL_Validaciones_UsuarioNull {
            get {
                return ResourceManager.GetString("BitacoraBL_Validaciones_UsuarioNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente con CUIT &apos;{0}&apos; es incorrecto o no es valido en el sistema.
        /// </summary>
        internal static string BL_Validaciones_ClienteInvalido {
            get {
                return ResourceManager.GetString("BL_Validaciones_ClienteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente no puede ser nulo.
        /// </summary>
        internal static string BL_Validaciones_ClienteNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_ClienteNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo postal no puede ser nulo o vacio.
        /// </summary>
        internal static string BL_Validaciones_CPNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_CPNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El CUIT no puede ser nulo o vacio.
        /// </summary>
        internal static string BL_Validaciones_CUITNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_CUITNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El domicilio no puede ser nulo o vacio.
        /// </summary>
        internal static string BL_Validaciones_DomicilioNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_DomicilioNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email no puede ser nulo o vacio.
        /// </summary>
        internal static string BL_Validaciones_EmailNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_EmailNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ingrediente &apos;{0}&apos; no existe.
        /// </summary>
        internal static string BL_Validaciones_IngredienteInvalido {
            get {
                return ResourceManager.GetString("BL_Validaciones_IngredienteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ingrediente no puede ser nulo.
        /// </summary>
        internal static string BL_Validaciones_IngredienteNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_IngredienteNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad &apos;{0}&apos; es incorrecta o no es valida en el sistema.
        /// </summary>
        internal static string BL_Validaciones_LocalidadInvalida {
            get {
                return ResourceManager.GetString("BL_Validaciones_LocalidadInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad no puede ser nula.
        /// </summary>
        internal static string BL_Validaciones_LocalidadNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_LocalidadNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de compra es incorrecta o no es valida en el sistema.
        /// </summary>
        internal static string BL_Validaciones_OrdenCompraInvalida {
            get {
                return ResourceManager.GetString("BL_Validaciones_OrdenCompraInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de compra no puede ser nula.
        /// </summary>
        internal static string BL_Validaciones_OrdenCompraNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_OrdenCompraNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de pago es incorrecta o no es valida en el sistema.
        /// </summary>
        internal static string BL_Validaciones_OrdenPagoInvalida {
            get {
                return ResourceManager.GetString("BL_Validaciones_OrdenPagoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de pago no puede ser nula.
        /// </summary>
        internal static string BL_Validaciones_OrdenPagoNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_OrdenPagoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de venta es incorrecta o no es valida en el sistema.
        /// </summary>
        internal static string BL_Validaciones_OrdenVentaInvalida {
            get {
                return ResourceManager.GetString("BL_Validaciones_OrdenVentaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de venta no puede ser nula.
        /// </summary>
        internal static string BL_Validaciones_OrdenVentaNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_OrdenVentaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de venta debe tener al menos un comensal.
        /// </summary>
        internal static string BL_Validaciones_OrdenVentaSinComensales {
            get {
                return ResourceManager.GetString("BL_Validaciones_OrdenVentaSinComensales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de venta debe tener al menos una receta.
        /// </summary>
        internal static string BL_Validaciones_OrdenVentaSinRecetas {
            get {
                return ResourceManager.GetString("BL_Validaciones_OrdenVentaSinRecetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proveedor con CUIT &apos;{0}&apos; es incorrecto o no es valido en el sistema.
        /// </summary>
        internal static string BL_Validaciones_ProveedorInvalido {
            get {
                return ResourceManager.GetString("BL_Validaciones_ProveedorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proveedor no puede ser nulo.
        /// </summary>
        internal static string BL_Validaciones_ProveedorNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_ProveedorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La provincia es incorrecta o no es valida en el sistema.
        /// </summary>
        internal static string BL_Validaciones_ProvinciaInvalida {
            get {
                return ResourceManager.GetString("BL_Validaciones_ProvinciaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La provincia no puede ser nula.
        /// </summary>
        internal static string BL_Validaciones_ProvinciaNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_ProvinciaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La receta &apos;{0}&apos; no existe.
        /// </summary>
        internal static string BL_Validaciones_RecetaInvalida {
            get {
                return ResourceManager.GetString("BL_Validaciones_RecetaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La receta no puede ser nula.
        /// </summary>
        internal static string BL_Validaciones_RecetaNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_RecetaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El telefono no puede ser nulo o vacio.
        /// </summary>
        internal static string BL_Validaciones_TelefonoNull {
            get {
                return ResourceManager.GetString("BL_Validaciones_TelefonoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La unidad &apos;{0}&apos; es incorrecta o no es valida en el sistema.
        /// </summary>
        internal static string BL_Validaciones_UnidadMedidaInvalida {
            get {
                return ResourceManager.GetString("BL_Validaciones_UnidadMedidaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del cliente no puede ser nulo o vacio.
        /// </summary>
        internal static string ClientesBL_Validaciones_NombreNull {
            get {
                return ResourceManager.GetString("ClientesBL_Validaciones_NombreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo &apos;{0}&apos; es incorrecto o no es valido en el sistema.
        /// </summary>
        internal static string ClientesBL_Validaciones_TipoInvalido {
            get {
                return ResourceManager.GetString("ClientesBL_Validaciones_TipoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede restaurar la Base de Datos porque el archivo &apos;{0}&apos; no existe.
        /// </summary>
        internal static string ContextoNegocio_Restaurar_BDNoExiste {
            get {
                return ResourceManager.GetString("ContextoNegocio_Restaurar_BDNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El empleado con CUIT &apos;{0}&apos; no existe.
        /// </summary>
        internal static string EmpleadosBL_Validaciones_CUITInvalido {
            get {
                return ResourceManager.GetString("EmpleadosBL_Validaciones_CUITInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El empleado no puede ser nulo.
        /// </summary>
        internal static string EmpleadosBL_Validaciones_EmpleadoNull {
            get {
                return ResourceManager.GetString("EmpleadosBL_Validaciones_EmpleadoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del empleado no puede ser nulo o vacio.
        /// </summary>
        internal static string EmpleadosBL_Validaciones_NombreNull {
            get {
                return ResourceManager.GetString("EmpleadosBL_Validaciones_NombreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente no puede ser nulo.
        /// </summary>
        internal static string FacturasBL_Validaciones_ClienteNull {
            get {
                return ResourceManager.GetString("FacturasBL_Validaciones_ClienteNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura a actualizar no existe en el sistema.
        /// </summary>
        internal static string FacturasBL_Validaciones_FacturaInvalida {
            get {
                return ResourceManager.GetString("FacturasBL_Validaciones_FacturaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura no puede ser nula.
        /// </summary>
        internal static string FacturasBL_Validaciones_FacturaNull {
            get {
                return ResourceManager.GetString("FacturasBL_Validaciones_FacturaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del ingrediente no puede ser nulo.
        /// </summary>
        internal static string IngredientesBL_Validaciones_NombreIngredienteNull {
            get {
                return ResourceManager.GetString("IngredientesBL_Validaciones_NombreIngredienteNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado &apos;{0}&apos; es incorrecto o no es valido en el sistema.
        /// </summary>
        internal static string OrdenesCompraBL_Validaciones_EstadoInvalido {
            get {
                return ResourceManager.GetString("OrdenesCompraBL_Validaciones_EstadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ingrediente &apos;{0}&apos; es incorrecto o no es valido en el sistema para la receta &apos;{1}&apos;.
        /// </summary>
        internal static string OrdenesCompraBL_Validaciones_IngredienteInvalido {
            get {
                return ResourceManager.GetString("OrdenesCompraBL_Validaciones_IngredienteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de compra debe tener al menos un item.
        /// </summary>
        internal static string OrdenesCompraBL_Validaciones_OrdenCompraSinItems {
            get {
                return ResourceManager.GetString("OrdenesCompraBL_Validaciones_OrdenCompraSinItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de venta asociada a la orden de compra no puede ser nula.
        /// </summary>
        internal static string OrdenesCompraBL_Validaciones_OrdenVentaNull {
            get {
                return ResourceManager.GetString("OrdenesCompraBL_Validaciones_OrdenVentaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad del ingrediente &apos;{0}&apos; para la receta &apos;{1}&apos; tienen que ser mayor a cero.
        /// </summary>
        internal static string OrdenesCompraBL_Validaciones_RecetaSinIngredientes {
            get {
                return ResourceManager.GetString("OrdenesCompraBL_Validaciones_RecetaSinIngredientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El item de orden de compra asociado a la orden de pago es incorrecto o no es valido en el sistema.
        /// </summary>
        internal static string OrdenesPagoBL_Validaciones_ItemOrdenCompraInvalido {
            get {
                return ResourceManager.GetString("OrdenesPagoBL_Validaciones_ItemOrdenCompraInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de pago debe tener al menos un item.
        /// </summary>
        internal static string OrdenesPagoBL_Validaciones_OrdenPagoSinItems {
            get {
                return ResourceManager.GetString("OrdenesPagoBL_Validaciones_OrdenPagoSinItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La receta &apos;{0}&apos; es incorrecta o no es valida en el sistema para la orden de venta.
        /// </summary>
        internal static string OrdenesVentaBL_Validaciones_RecetaInvalida {
            get {
                return ResourceManager.GetString("OrdenesVentaBL_Validaciones_RecetaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El item de la lista de precios es incorrecto o no es valido en el sistema.
        /// </summary>
        internal static string PreciosIngredientesBL_Validaciones_ItemInvalido {
            get {
                return ResourceManager.GetString("PreciosIngredientesBL_Validaciones_ItemInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El item de la lista de precios no puede ser nulo.
        /// </summary>
        internal static string PreciosIngredientesBL_Validaciones_ItemNull {
            get {
                return ResourceManager.GetString("PreciosIngredientesBL_Validaciones_ItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del proveedor no puede ser nulo o vacio.
        /// </summary>
        internal static string ProveedoresBL_Validaciones_NombreNull {
            get {
                return ResourceManager.GetString("ProveedoresBL_Validaciones_NombreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la receta no puede ser nulo o vacio.
        /// </summary>
        internal static string RecetasBL_Validaciones_NombreNull {
            get {
                return ResourceManager.GetString("RecetasBL_Validaciones_NombreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La receta debe tener al menos un ingrediente.
        /// </summary>
        internal static string RecetasBL_Validaciones_SinIngredientes {
            get {
                return ResourceManager.GetString("RecetasBL_Validaciones_SinIngredientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nick del usuario no puede ser nulo o vacio.
        /// </summary>
        internal static string UsuariosBL_Validaciones_NickNull {
            get {
                return ResourceManager.GetString("UsuariosBL_Validaciones_NickNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario no puede ser nulo o vacio.
        /// </summary>
        internal static string UsuariosBL_Validaciones_NombreNull {
            get {
                return ResourceManager.GetString("UsuariosBL_Validaciones_NombreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El password no puede ser nulo o vacio.
        /// </summary>
        internal static string UsuariosBL_Validaciones_PasswordNull {
            get {
                return ResourceManager.GetString("UsuariosBL_Validaciones_PasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El perfil &apos;{0}&apos; es incorrecto o no es valido en el sistema.
        /// </summary>
        internal static string UsuariosBL_Validaciones_PerfilInvalido {
            get {
                return ResourceManager.GetString("UsuariosBL_Validaciones_PerfilInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario &apos;{0}&apos; no existe.
        /// </summary>
        internal static string UsuariosBL_Validaciones_UsuarioInvalido {
            get {
                return ResourceManager.GetString("UsuariosBL_Validaciones_UsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no puede ser nulo.
        /// </summary>
        internal static string UsuariosBL_Validaciones_UsuarioNull {
            get {
                return ResourceManager.GetString("UsuariosBL_Validaciones_UsuarioNull", resourceCulture);
            }
        }
    }
}
