//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBMCatering.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredienteReceta
    {
        public int IDReceta { get; set; }
        public int IDIngrediente { get; set; }
        public decimal Cantidad { get; set; }
        public int IDUnidadMedida { get; set; }
    
        public virtual Ingrediente Ingrediente { get; set; }
        public virtual Receta Receta { get; set; }
        public virtual UnidadMedida Unidad { get; set; }
    }
}
